# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalogo.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61talogo.proto\x12\x08\x63\x61talogo\"!\n\x07Session\x12\x16\n\x0esession_cookie\x18\x01 \x01(\t\"\x19\n\x07IdLivro\x12\x0e\n\x06titulo\x18\x01 \x01(\t\":\n\x0cListCarrinho\x12*\n\x0flivros_carrinho\x18\x01 \x03(\x0b\x32\x11.catalogo.IdLivro\"\x81\x01\n\x04\x42ook\x12\x10\n\x08\x63\x61rrinho\x18\x01 \x01(\x08\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\r\n\x05\x61utor\x18\x03 \x01(\t\x12\x12\n\npublicacao\x18\x04 \x01(\x05\x12\x12\n\nem_estoque\x18\x05 \x01(\x05\x12\r\n\x05preco\x18\x06 \x01(\x05\x12\x11\n\tdescricao\x18\x07 \x01(\t\"-\n\x0c\x46ullCatalogo\x12\x1d\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0e.catalogo.Book\".\n\x0eSuccessMessage\x12\t\n\x01m\x18\x01 \x01(\t\x12\x11\n\tid_pedido\x18\x02 \x01(\t2\x8c\x01\n\x0cShowCatalogo\x12\x38\n\x0bGetCatalogo\x12\x11.catalogo.Session\x1a\x16.catalogo.FullCatalogo\x12\x42\n\x0eUpdateCatalogo\x12\x16.catalogo.ListCarrinho\x1a\x18.catalogo.SuccessMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalogo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSION']._serialized_start=28
  _globals['_SESSION']._serialized_end=61
  _globals['_IDLIVRO']._serialized_start=63
  _globals['_IDLIVRO']._serialized_end=88
  _globals['_LISTCARRINHO']._serialized_start=90
  _globals['_LISTCARRINHO']._serialized_end=148
  _globals['_BOOK']._serialized_start=151
  _globals['_BOOK']._serialized_end=280
  _globals['_FULLCATALOGO']._serialized_start=282
  _globals['_FULLCATALOGO']._serialized_end=327
  _globals['_SUCCESSMESSAGE']._serialized_start=329
  _globals['_SUCCESSMESSAGE']._serialized_end=375
  _globals['_SHOWCATALOGO']._serialized_start=378
  _globals['_SHOWCATALOGO']._serialized_end=518
# @@protoc_insertion_point(module_scope)
