# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalogo.catalogo_pb2 as catalogo__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in catalogo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ShowCatalogoStub(object):
    """Definicao do servico do catalogo, com opcao de retornar todos os livros ou alterar livros comprados
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCatalogo = channel.unary_unary(
                '/catalogo.ShowCatalogo/GetCatalogo',
                request_serializer=catalogo__pb2.Session.SerializeToString,
                response_deserializer=catalogo__pb2.FullCatalogo.FromString,
                _registered_method=True)
        self.UpdateCatalogo = channel.unary_unary(
                '/catalogo.ShowCatalogo/UpdateCatalogo',
                request_serializer=catalogo__pb2.ListCarrinho.SerializeToString,
                response_deserializer=catalogo__pb2.SuccessMessage.FromString,
                _registered_method=True)


class ShowCatalogoServicer(object):
    """Definicao do servico do catalogo, com opcao de retornar todos os livros ou alterar livros comprados
    """

    def GetCatalogo(self, request, context):
        """Funcao que deve retornar todos os livros disponiveis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCatalogo(self, request, context):
        """Funcao que deve alterar o estoque apos uma comprar e retorna mensagem de sucesso
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowCatalogoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCatalogo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatalogo,
                    request_deserializer=catalogo__pb2.Session.FromString,
                    response_serializer=catalogo__pb2.FullCatalogo.SerializeToString,
            ),
            'UpdateCatalogo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCatalogo,
                    request_deserializer=catalogo__pb2.ListCarrinho.FromString,
                    response_serializer=catalogo__pb2.SuccessMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalogo.ShowCatalogo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalogo.ShowCatalogo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShowCatalogo(object):
    """Definicao do servico do catalogo, com opcao de retornar todos os livros ou alterar livros comprados
    """

    @staticmethod
    def GetCatalogo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.ShowCatalogo/GetCatalogo',
            catalogo__pb2.Session.SerializeToString,
            catalogo__pb2.FullCatalogo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCatalogo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.ShowCatalogo/UpdateCatalogo',
            catalogo__pb2.ListCarrinho.SerializeToString,
            catalogo__pb2.SuccessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
