# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import addsub_pb2 as addsub__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in addsub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AddSubStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoAdd = channel.unary_unary(
                '/addsub.AddSub/DoAdd',
                request_serializer=addsub__pb2.OpParam.SerializeToString,
                response_deserializer=addsub__pb2.OpResults.FromString,
                _registered_method=True)
        self.DoSub = channel.unary_unary(
                '/addsub.AddSub/DoSub',
                request_serializer=addsub__pb2.OpParam.SerializeToString,
                response_deserializer=addsub__pb2.OpResults.FromString,
                _registered_method=True)


class AddSubServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoSub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddSubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.DoAdd,
                    request_deserializer=addsub__pb2.OpParam.FromString,
                    response_serializer=addsub__pb2.OpResults.SerializeToString,
            ),
            'DoSub': grpc.unary_unary_rpc_method_handler(
                    servicer.DoSub,
                    request_deserializer=addsub__pb2.OpParam.FromString,
                    response_serializer=addsub__pb2.OpResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'addsub.AddSub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('addsub.AddSub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AddSub(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/addsub.AddSub/DoAdd',
            addsub__pb2.OpParam.SerializeToString,
            addsub__pb2.OpResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DoSub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/addsub.AddSub/DoSub',
            addsub__pb2.OpParam.SerializeToString,
            addsub__pb2.OpResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
