# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addsub.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x64\x64sub.proto\x12\x06\x61\x64\x64sub\"%\n\x07OpParam\x12\x0c\n\x04val1\x18\x01 \x01(\x05\x12\x0c\n\x04val2\x18\x02 \x01(\x05\"\x1b\n\tOpResults\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x62\n\x06\x41\x64\x64Sub\x12+\n\x05\x44oAdd\x12\x0f.addsub.OpParam\x1a\x11.addsub.OpResults\x12+\n\x05\x44oSub\x12\x0f.addsub.OpParam\x1a\x11.addsub.OpResultsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addsub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPPARAM']._serialized_start=24
  _globals['_OPPARAM']._serialized_end=61
  _globals['_OPRESULTS']._serialized_start=63
  _globals['_OPRESULTS']._serialized_end=90
  _globals['_ADDSUB']._serialized_start=92
  _globals['_ADDSUB']._serialized_end=190
# @@protoc_insertion_point(module_scope)
