# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"4\n\x08UserData\x12\x13\n\x0blogin_email\x18\x01 \x01(\t\x12\x13\n\x0blogin_senha\x18\x02 \x01(\t\"J\n\rLoginResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x12\x16\n\x0esession_cookie\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2o\n\x08UserAuth\x12\x31\n\nCreateUser\x12\x0e.auth.UserData\x1a\x13.auth.LoginResponse\x12\x30\n\tLoginUser\x12\x0e.auth.UserData\x1a\x13.auth.LoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDATA']._serialized_start=20
  _globals['_USERDATA']._serialized_end=72
  _globals['_LOGINRESPONSE']._serialized_start=74
  _globals['_LOGINRESPONSE']._serialized_end=148
  _globals['_USERAUTH']._serialized_start=150
  _globals['_USERAUTH']._serialized_end=261
# @@protoc_insertion_point(module_scope)
