# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gestao.gestao_pb2 as gestao__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gestao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GestaoPedidosStub(object):
    """Servico que permite gestao de pedidos no server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarPedido = channel.unary_unary(
                '/gestao.GestaoPedidos/ConsultarPedido',
                request_serializer=gestao__pb2.DadosConsulta.SerializeToString,
                response_deserializer=gestao__pb2.StatusPedido.FromString,
                _registered_method=True)
        self.ConsultarHistorico = channel.unary_unary(
                '/gestao.GestaoPedidos/ConsultarHistorico',
                request_serializer=gestao__pb2.DadosUser.SerializeToString,
                response_deserializer=gestao__pb2.HistorioUser.FromString,
                _registered_method=True)


class GestaoPedidosServicer(object):
    """Servico que permite gestao de pedidos no server
    """

    def ConsultarPedido(self, request, context):
        """Funcao que deve receber session e id do pedido para retornar dados dele
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarHistorico(self, request, context):
        """Funcao que deve receber session do user e retornar todos o pedidos daquela session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GestaoPedidosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarPedido,
                    request_deserializer=gestao__pb2.DadosConsulta.FromString,
                    response_serializer=gestao__pb2.StatusPedido.SerializeToString,
            ),
            'ConsultarHistorico': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarHistorico,
                    request_deserializer=gestao__pb2.DadosUser.FromString,
                    response_serializer=gestao__pb2.HistorioUser.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gestao.GestaoPedidos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gestao.GestaoPedidos', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GestaoPedidos(object):
    """Servico que permite gestao de pedidos no server
    """

    @staticmethod
    def ConsultarPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestao.GestaoPedidos/ConsultarPedido',
            gestao__pb2.DadosConsulta.SerializeToString,
            gestao__pb2.StatusPedido.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarHistorico(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestao.GestaoPedidos/ConsultarHistorico',
            gestao__pb2.DadosUser.SerializeToString,
            gestao__pb2.HistorioUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
